<div class="maincomp">
                                                                        <div class="component-pad">

<div id="showcase" class="dp100">
			<div class="background"></div>
			<div class="foreground">
		    	<div class="mainphead">get pure results &amp;</div>

<div class="mainphead1">feel the power</div>

<p style="margin-top:0px;"><img src="/images/stories/mainpic.jpg" border="0" /></p>

<div class="mainpbutton"><a href="#">see whats inside</a></div>
		    </div>
		</div>
		        		<div id="showcase1">
			<div class="background"></div>
			<div class="foreground">
		    	

<div id="slideshow-1-4fbc6ae769b63" class="wk-slideshow wk-slideshow-default" data-widgetkit="slideshow" data-options='{"style":"default","autoplay":1,"interval":5000,"width":380,"height":516,"duration":500,"index":0,"order":"default","navigation":0,"buttons":0,"slices":20,"animated":"scrollLeft","caption_animation_duration":500}'>

	<div>

		<ul class="slides">



									<li>

				<article class="wk-content clearfix"><img src="/images/stories/slider/slideimg1.jpg" border="0" />

<div class="pname">Multivitamin</div>

<div class="pname1">complex</div>

<div class="seemore"><a href="#">see more ></a></div>

<div class="social">

<div style="width: 206px; height: 24px;margin:0 auto;">

	<a class="twitter-share-button" data-via="ovclinicalsops" href="https://twitter.com/share">Tweet</a><iframe allowtransparency="" frameborder="0" scrolling="no" src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2F%23%21%2Fpages%2FOV-Clinical-Trials%2F195827167105791%3Fnotif_t%3Dpage_new_likes&send=false&layout=button_count&width=450&show_faces=false&action=like&colorscheme=light&font&height=21" style="border-bottom: medium none; border-left: medium none; width: 96px; height: 21px; overflow: hidden; border-top: medium none; border-right: medium none"></iframe></div>

<p>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>



</div>

</article>

			</li>

												<li>

				<article class="wk-content clearfix"><img src="data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP///////wAAACH5BAEHAAIALAAAAAABAAEAAAICVAEAOw==" data-src="/images/stories/slider/slideimg1.jpg" border="0" />

<div class="pname">Multivitamin</div>

<div class="pname1">complex</div>

<div class="seemore"><a href="#">see more ></a></div>

<div class="social">

<div style="width: 206px; height: 24px;margin:0 auto;">

	<a class="twitter-share-button" data-via="ovclinicalsops" href="https://twitter.com/share">Tweet</a><iframe allowtransparency="" frameborder="0" scrolling="no" src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2F%23%21%2Fpages%2FOV-Clinical-Trials%2F195827167105791%3Fnotif_t%3Dpage_new_likes&send=false&layout=button_count&width=450&show_faces=false&action=like&colorscheme=light&font&height=21" style="border-bottom: medium none; border-left: medium none; width: 96px; height: 21px; overflow: hidden; border-top: medium none; border-right: medium none"></iframe></div>

<p>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>



</div></article>

			</li>

												<li>

				<article class="wk-content clearfix"><img src="data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP///////wAAACH5BAEHAAIALAAAAAABAAEAAAICVAEAOw==" data-src="/images/stories/slider/slideimg1.jpg" border="0" />

<div class="pname">Multivitamin</div>

<div class="pname1">complex</div>

<div class="seemore"><a href="#">see more ></a></div>

<div class="social">

<div style="width: 206px; height: 24px;margin:0 auto;">

	<a class="twitter-share-button" data-via="ovclinicalsops" href="https://twitter.com/share">Tweet</a><iframe allowtransparency="" frameborder="0" scrolling="no" src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2F%23%21%2Fpages%2FOV-Clinical-Trials%2F195827167105791%3Fnotif_t%3Dpage_new_likes&send=false&layout=button_count&width=450&show_faces=false&action=like&colorscheme=light&font&height=21" style="border-bottom: medium none; border-left: medium none; width: 96px; height: 21px; overflow: hidden; border-top: medium none; border-right: medium none"></iframe></div>

<p>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>



</div></article>

			</li>

								</ul>

				<div class="caption"></div><ul class="captions"><li></li><li></li><li></li></ul>

	</div>

	</div>
		    </div>
		</div>
</div>
      </div>		