<div id="content">
	<div class="one">
		<div class="slideshow">
			<div id="slides">
				<div id="slider-big">
					<div class="slides_container big-slider">
						<!-- SLIDER STARTS-->
						<!-- SLIDER CONTENT STARTS-->
						<img src="/themes/adventure/images/slideshow/slide-02.jpg" alt=" " width="950" height="350"/>
						<div class="slide">
						<img src="/themes/adventure/images/slideshow/slide-03.jpg" alt=" " width="950" height="350"/>
						<div class="caption">
							<p>Your Caption Goes Here!</p>
						</div>
					</div>
					<img src="/themes/adventure/images/slideshow/slide-01.jpg" alt=" " width="950" height="350"/>
				</div>
				<!-- SLIDESHOW CONTAINER ENDS-->
			</div>
			<div class="slides-nav">

    			<a href="#" class="prev">Previous Slide</a>
    			<a href="#" class="next">Next Slide</a>

				<!--END .slides-nav -->
			</div>
		</div>
	</div><!-- SLIDER ENDS-->	<!-- SLIDESHOW ENDS-->
</div>

<div class="one">
	<!-- COLUMNS CONTAINER STARTS-->
	<div class="intro-pages">

		<!-- INTRO DIV STARTS-->
		<?php echo $this->editable('welcome_intro', 'text','<h3>Welcome to <span class="colored">Adventure</span>, Clean &amp; Simple <span class="colored">HTML5 </span> template.Feel free to browse through all the pages and see what\'s &quot;Adventure&quot; capable to do for You.Enjoy! </h3>'); ?>

	</div>
	<!-- INTRO ENDS-->
</div>
<!-- COLUMNS CONTAINER ENDS-->

<div class="one">
	<div class="one-third">
		<img src="/themes/adventure/images/icons/idea.png" alt=" " class="img-align-left" width="66" height="66"/>
		<?php echo $this->editable('index-intro-1', 'text','
		<div class="text-align-left">
			<h4>Easy to Customize</h4>
			<p>
				Iuraveras magnifice ex auxilium super color est cum. Ripae simul navigat est amet constanter approximavit te.
			</p>
		</div>
		'); ?>
	</div>
	<div class="one-third">
		<img src="/themes/adventure/images/icons/display.png" alt=" " class="img-align-left" width="66" height="66"/>
		<?php echo $this->editable('index-intro-2', 'text','
		<div class="text-align-left">
			<h4>Browsers Compatible</h4>
			<p>
				Iuraveras magnifice ex auxilium super color est cum. Ripae simul navigat est amet constanter approximavit te.
			</p>
		</div>
		'); ?>
	</div>
	<div class="one-third last">
		<img src="/themes/adventure/images/icons/check-box.png" alt=" " class="img-align-left" width="66" height="66"/>
		<?php echo $this->editable('index-intro-3', 'text','
		<div class="text-align-left">
			<h4>Full Documentation</h4>
			<p>
				Iuraveras magnifice ex auxilium super color est cum. Ripae simul navigat est amet constanter approximavit te.
			</p>
		</div>
		'); ?>
	</div>
</div>







