<div class="maincomp">
                                                                        <div class="component-pad">

<div id="showcase" class="dp100">
			<div class="background"></div>
			<div class="foreground">
		    	<div class="mainphead">get pure results &amp;</div>

<div class="mainphead1"><a class="main_header" href="/page/about/">feel the power</a></div>

<p style="margin-top:0px;"><img src="/images/stories/mainpic.jpg" border="0" /></p>

<div class="mainpbutton"><a href="#">see whats inside</a></div>
		    </div>
		</div>
		        		<div id="showcase1">
			<div class="background"></div>
			<div class="foreground">
		    	

<div id="slideshow-1-4fbc6ae769b63" class="wk-slideshow wk-slideshow-default" data-widgetkit="slideshow" data-options='{"style":"default","autoplay":1,"interval":5000,"width":380,"height":516,"duration":500,"index":0,"order":"default","navigation":0,"buttons":0,"slices":20,"animated":"scrollLeft","caption_animation_duration":500}'>

	<div>

		<ul class="slides">



									<li>

				<article class="wk-content clearfix"><img src="/images/stories/slider/slideimg1.jpg" border="0" />

<div class="pname">Multivitamin</div>

<div class="pname1">complex</div>

<div class="seemore"><a href="#">see more ></a></div>
</article>

			</li>

												<li>

				<article class="wk-content clearfix"><img src="data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP///////wAAACH5BAEHAAIALAAAAAABAAEAAAICVAEAOw==" data-src="/images/stories/slider/slideimg1.jpg" border="0" />

<div class="pname">Multivitamin</div>

<div class="pname1">complex</div>

<div class="seemore"><a href="#">see more ></a></div>

</article>

			</li>

												<li>

				<article class="wk-content clearfix"><img src="data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP///////wAAACH5BAEHAAIALAAAAAABAAEAAAICVAEAOw==" data-src="/images/stories/slider/slideimg1.jpg" border="0" />

<div class="pname">Multivitamin</div>

<div class="pname1">complex</div>

<div class="seemore"><a href="#">see more ></a></div>

</article>

			</li>

								</ul>

				<div class="caption"></div><ul class="captions"><li></li><li></li><li></li></ul>

	</div>

	</div>
		    </div>
		</div>
</div>
      </div>		