
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" >
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="robots" content="index, follow" />
  <meta name="keywords" content="joomla, Joomla" />
  <meta name="description" content="Joomla! - the dynamic portal engine and content management system" />
  <meta name="generator" content="Joomla! 1.5 - Open Source Content Management" />
  <title>Welcome to the Frontpage</title>
  <link href="/index.php?option=com_content&amp;view=frontpage&amp;Itemid=1&amp;format=feed&amp;type=rss" rel="alternate" type="application/rss+xml" title="RSS 2.0" />
  <link href="/index.php?option=com_content&amp;view=frontpage&amp;Itemid=1&amp;format=feed&amp;type=atom" rel="alternate" type="application/atom+xml" title="Atom 1.0" />
  <link rel="stylesheet" href="/css/modal.css" type="text/css" />
  <link rel="stylesheet" href="/css/k2.css" type="text/css" />
  <link rel="stylesheet" href="/css/widgetkit.css" type="text/css" />
  <link rel="stylesheet" href="/css/module_default.css" type="text/css" />
  <style type="text/css">
    <!--

	#wrapper { margin: 0 auto; width: 962px;padding:0;}
	.s-c-s #colmid { left:0px;}
	.s-c-s #colright { margin-left:-0px;}
	.s-c-s #col1pad { margin-left:0px;}
	.s-c-s #col2 { left:0px;width:0px;}
	.s-c-s #col3 { width:0px;}
	
	.s-c-x #colright { left:0px;}
	.s-c-x #col1wrap { right:0px;}
	.s-c-x #col1 { margin-left:0px;}
	.s-c-x #col2 { right:0px;width:0px;}
	
	.x-c-s #colright { margin-left:-0px;}
	.x-c-s #col1 { margin-left:0px;}
	.x-c-s #col3 { left:0px;width:0px;}
    -->
  </style>
  <script type="text/javascript" src="/js/mootools.js"></script>
  <script type="text/javascript" src="/js/modal.js"></script>
  <script type="text/javascript" src="/js/jquery.min.js"></script>
  <script type="text/javascript" src="/js/k2.js"></script>
  <script type="text/javascript" src="/js/jquery.js"></script>
  <script type="text/javascript" src="/js/widgetkit.js"></script>
  <script type="text/javascript" src="/js/acymailing_module.js"></script>
  <script type="text/javascript">

		window.addEvent('domready', function() {

			SqueezeBox.initialize({});

			$$('a.modal').each(function(el) {
				el.addEvent('click', function(e) {
					new Event(e).stop();
					SqueezeBox.fromElement(el);
				});
			});
		});
var K2SitePath = '/';
<!--

					var acymailing = Array();

					acymailing['NAMECAPTION'] = 'Name';

					acymailing['NAME_MISSING'] = 'Please enter your name';

					acymailing['EMAILCAPTION'] = 'enter your email...';

					acymailing['VALID_EMAIL'] = 'Please enter a valid e-mail address';

					acymailing['ACCEPT_TERMS'] = 'Please check the Terms and Conditions';

					acymailing['CAPTCHA_MISSING'] = 'Please enter the security code displayed in the image';

					acymailing['NO_LIST_SELECTED'] = 'Please select the lists you want to subscribe to';

			//-->
  </script>

<link rel="stylesheet" href="/css/light4.css" type="text/css" />
<!--[if lte IE 6]>
<script type="text/javascript" src="/templates/rt_afterburner_j15/js/ie_suckerfish.js"></script>
<link rel="stylesheet" href="/templates/rt_afterburner_j15/css/styles.ie.css" type="text/css" />
<![endif]-->
<!--[if lte IE 7]>
<link rel="stylesheet" href="/templates/rt_afterburner_j15/css/styles.ie7.css" type="text/css" />
<![endif]-->
</head>
<body class="default">
<div class="background"></div>
<div id="main">
	<div id="wrapper" class="foreground">
	    <div id="message">
		    
		</div>
        <div id="header">
    		<div id="mlogo">		
    	    <a href="/" id="logo"></a>
            </div>
            <div id="nav">
                 <div id="menu">
		         <ul id="mainlevel-nav">
		         	<li><a href="/" class="mainlevel-nav" <?php if($this->page == 'home'){ echo 'id="active_menu-nav"'; }?>>Home</a></li>
		         	<li><span class="mainlevel-nav" >/</span></li>
		         	<li><a href="/page/about" class="mainlevel-nav" <?php if($this->page == 'about'){ echo 'id="active_menu-nav"'; }?>>About</a></li>
		         	<li><span class="mainlevel-nav" >/</span></li>
		         	<li><a href="/page/products" class="mainlevel-nav" <?php if($this->page == 'products' || $this->page == 'product'){ echo 'id="active_menu-nav"'; }?>>Products</a></li>
		         	<li><span class="mainlevel-nav" >/</span></li>
		         	<li><a href="/page/contact" class="mainlevel-nav" <?php if($this->page == 'contact'){ echo 'id="active_menu-nav"'; }?>>Contact</a></li>
		         	<li><span class="mainlevel-nav" >/</span></li>
		         	<li><a href="/blog" class="mainlevel-nav" <?php if($this->page == 'blog'){ echo 'id="active_menu-nav"'; }?> >Blog</a></li></ul>
                 </div>
                 <div id="lang">
                 <p>Lang US</p>
                 </div>
		    </div>
		</div>
		<div style="clear:both;"></div>
        <div id="title">
        
        </div>
		
				
		
        <div id="main-content" class="x-c-x">
            <div id="colmask" class="ckl-color2">
                <div id="colmid" class="cdr-color1">
                    <div id="colright" class="ctr-color1">
                        <div id="col1wrap">
							<div id="col1pad">
                            	<div id="col1">
									                                    
      
                                        <?php echo $this->layout()->content;?>
                                    
      <div class="sidemod">
      
      </div>
      <div style="clear:both;"></div>
      <div id="abtmod1">
      
      </div>
      <div id="abtmod2">
      
      </div>
      <div id="abtmod3">
      
      </div>
      <div style="clear:both;"></div>
      
      <div id="abtmod4">
      
      </div>
      <div id="abtmod5">
      
      </div>
      <div id="abtmod6">
      
      </div>
       <div style="clear:both;"></div>                             
																		<div id="mainmods" class="spacer w33">
												<div class="module m_mod">
		
			    <div class="module-body">
	        <img src="/images/stories/cycle.jpg" />        </div>
	</div>
	
												<div class="module m_social">
		
			    <div class="module-body">
	        <div class="social"><h1>Stay<br /> Tuned<br /></h1>

<a href="#"><img src="/images/stories/youtube.png" /></a><br /><br />

<a href="#"><img src="/images/stories/facebook.png" /></a>

<a href="#"><img src="/images/stories/twitter.png" /></a>

<br />

<br />

<br />

</div>        </div>
	</div>
	
												<div class="module m_pure">
		
			    <div class="module-body">
	        <div>

<h1>Get Pure<br />Results</h1>

<img src="/images/stories/botimg.jpg" />

<p></p>



</div>        </div>
	</div>
	
                                        		<div class="module m_news">
		
				<h3 class="module-title">Newsletter sign up!</h3>
			    <div class="module-body">
	        <div class="acymailing_module_news" id="acymailing_module_formAcymailing1">

	<div class="acymailing_fulldiv" id="acymailing_fulldiv_formAcymailing1" style="text-align:center" >

		<form id="formAcymailing1" action="/index.php?option=com_content&amp;view=frontpage&amp;Itemid=1" onsubmit="return submitacymailingform('optin','formAcymailing1')" method="post" name="formAcymailing1"  >

		<div class="acymailing_module_form" >

									<table class="acymailing_form">

				<tr>

												<td class="acyfield_email">

								<input id="user_email_formAcymailing1"  onfocus="if(this.value == 'enter your email...') this.value = '';" onblur="if(this.value=='') this.value='enter your email...';" class="inputbox" type="text" name="user[email]" size="30" value="enter your email..." />

							</td> 					<td  class="acysubbuttons">

												<input class="button subbutton" type="submit" value="GO" name="Submit" onclick="try{ return submitacymailingform('optin','formAcymailing1'); }catch(err){alert('The form could not be submitted '+err);return false;}"/>

											</td>

				</tr>

			</table>

						<input type="hidden" name="ajax" value="0"/>

			<input type="hidden" name="ctrl" value="sub"/>

			<input type="hidden" name="task" value="notask"/>

			<input type="hidden" name="redirect" value="http%3A%2F%2Fuptownhr.dyndns.org%2Findex.php%3Foption%3Dcom_content%26view%3Dfrontpage%26Itemid%3D1"/>

			<input type="hidden" name="redirectunsub" value="http%3A%2F%2Fuptownhr.dyndns.org%2Findex.php%3Foption%3Dcom_content%26view%3Dfrontpage%26Itemid%3D1"/>

			<input type="hidden" name="option" value="com_acymailing"/>

						<input type="hidden" name="hiddenlists" value="1"/>

			<input type="hidden" name="acyformname" value="formAcymailing1" />

						<input type="hidden" name="Itemid" value="1"/>			</div>

		</form>

	</div>

	</div>        </div>
	</div>
			<div class="module m botmods">
		
			    <div class="module-body">
	        <img src="/images/stories/botmods.png" />        </div>
	</div>
	
									</div>
									                                    
																		<div id="mainmods2" class="spacer w33">
												<div class="module m readmore">
		
				<h3 class="module-title">Newsflash</h3>
			    <div class="module-body">
	        


<table class="contentpaneopen readmore">
	<tr>
		<td valign="top" ><p>Joomla! makes it easy to launch a Web site of any kind.</td>
	</tr>
	<tr>
        <td valign="top" >

       <a class="readmore" href="/index.php?option=com_content&amp;view=article&amp;id=2%3Anewsflash-1&amp;catid=3%3Anewsflash&amp;Itemid=1">read more ></a>		</td>
     </tr>
</table>
        </div>
	</div>
	
												<div class="module m info">
		
			    <div class="module-body">
	        <div style="float:left;font-size: 12px;">

<h3>COMPANY Info</h3>

Address Info and other info<br />

Lorem ipsum dolor sit amet, consectetur adipisicing<br /><br />

"Sed ut perspiciatis unde omnis iste natus error sit voluptatem<br />

accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo<br /><br /><br /><br />

</div>

<div style="float:right;">PURE RESULTS &trade;</div>        </div>
	</div>
	
									</div>
										                            </div>
							</div>
                        </div>
												                    </div>
                </div>
            </div>
        </div>
		
						
		
	</div>
</div>
</body>
</html>