<div id="title">
	<div class="module m contitle">

		<div class="module-body"
			style="font-size: 39px; font-family: HelveticaLTSTDBold; color: #3E3E3E; margin-top: 18px">
			Thank You!</div>
	</div>
</div>

<div style="background:white;padding:20px;width:100%;min-height:10em">
	<p><strong>Thank you for your order!</strong></p>
	<p>We will pack it and ship it ASAP!</p>
	<p><a href="/">Return Home</a>
</div>