<div id="title">
	<div class="module m contitle">

		<div class="module-body"
			style="font-size: 39px; font-family: HelveticaLTSTDBold; color: #3E3E3E; margin-top: 18px">
			Your Shopping Cart</div>
	</div>
</div>

<table width="100%" id="shopping-cart">
	<thead>
		<th>Product</th>
		<th>Size</th>
		<th>Price</th>
		<th>Qty</th>
		<th>Remove</th>
	</thead>
	<tr style="background: white;">
		<td>
			<a href="" target="_blank"><img src="" alt="" style="float: left;margin-right:10px"></a>
			<a href="" target="_blank">Product title</a>
		</td>
		<td>60 cap.</td>
		<td>$15.99</td>
		<td>2</td>
		<td><a href="#" style="font-size:11px">Remove</a></td>
	</tr>
	<tr style="background: white;">
		<td>
			<a href="" target="_blank"><img src="" alt="" style="float: left;margin-right:10px"></a>
			<a href="" target="_blank">Product title</a>
		</td>
		<td>60 cap.</td>
		<td>$15.99</td>
		<td>2</td>
		<td><a href="#" style="font-size:11px">Remove</a></td>
	</tr>
	<tr style="background: white;">
		<td>
			<a href="" target="_blank"><img src="" alt="" style="float: left;margin-right:10px"></a>
			<a href="" target="_blank">Product title</a>
		</td>
		<td>60 cap.</td>
		<td>$15.99</td>
		<td>2</td>
		<td><a href="#" style="font-size:11px">Remove</a></td>
	</tr>
	<tr style="background-color:transparent;border-bottom:none;">
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td style="text-align:right;font-weight:bold;">Subtotal</td>
		<td>$139.99</td>
	</tr>
</table>

<div style="text-align:center">
	<a href=""><button type="button" class="button">Proceed to Checkout</button></a> 
	<a href=""><button type="button" class="button">Continue Shopping</button></a>
</div>