<div id="title">
	<div class="module m contitle">

		<div class="module-body"
			style="font-size: 39px; font-family: HelveticaLTSTDBold; color: #3E3E3E; margin-top: 18px">
			Your Shopping Cart</div>
	</div>
</div>

<table width="100%" id="shopping-cart">
	<thead>
		<th>Product</th>
		<th>Size</th>
		<th>Price</th>
		<th>Qty</th>
		<th>Remove</th>
	</thead>
	<?php $sub_total = 0; foreach($_SESSION['cart'] as $key=>$item){ $sub_total += $item['product_size_price'];?>
	<tr style="background: white;">
		<td>
			<a href="/product/item/id/<?php echo $item['product_id'];?>" target="_blank"><?php echo $item['product_name'];?></a>
		</td>
		<td><?php echo $item['size'];?></td>
		<td>$<?php echo $item['product_size_price'];?></td>
		<td><?php echo $item['qty'];?></td>
		<td><a href="/cart/remove/key/<?php echo $key; ?>" style="font-size:11px">Remove</a></td>
	</tr>
	<?php }?>
	<tr style="background-color:transparent;border-bottom:none;">
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td style="text-align:right;font-weight:bold;">Subtotal</td>
		<td>$<?php echo $sub_total;?></td>
	</tr>
</table>

<div style="text-align:center">
	<a href="/cart/checkout"><button type="button" class="button shop">Proceed to Checkout</button></a> 
	<a href="/page/products"><button type="button" class="button">Continue Shopping</button></a>
</div>

<script>
$('.button.shop').click( function(e){
	e.preventDefault();
	console.log('test');
	window.location('/page/products');
});
</script>