<script>
$(document).ready(function(){
	var clickX = new Array();
	var clickY = new Array();
	var clickDrag = new Array();
	var paint;
	context = document.getElementById('canvasInAPerfectWorld').getContext("2d");
	canvas = document.getElementById('canvasInAPerfectWorld');
	canvas.height = $('#contents').height();
	canvas.width = $('#contents').width();
	$('#canvasInAPerfectWorld').mousedown(function(e){
	  var mouseX = e.pageX - this.offsetLeft;
	  var mouseY = e.pageY - this.offsetTop;
			
	  paint = true;
	  addClick(e.pageX - this.offsetLeft, e.pageY - this.offsetTop);
	  redraw();
	});
	$('#canvasInAPerfectWorld').mousemove(function(e){
		if(paint){
			addClick(e.pageX - this.offsetLeft, e.pageY - this.offsetTop, true);
			redraw();
		}
	});
	$('#canvasInAPerfectWorld').mouseup(function(e){
	  paint = false;
	  console.log('test');
	});
	
	$('#canvasInAPerfectWorld').mouseleave(function(e){
	  paint = false;
	});
	
	function addClick(x, y, dragging)
	{
	  clickX.push(x);
	  clickY.push(y);
	  clickDrag.push(dragging);
	}
	function redraw(){
	  canvas.width = canvas.width; // Clears the canvas
	  
	  context.strokeStyle = "#df4b26";
	  context.lineJoin = "round";
	  context.lineWidth = 5;
				
	  for(var i=0; i < clickX.length; i++)
	  {		
		context.beginPath();
		if(clickDrag[i] && i){
		  context.moveTo(clickX[i-1], clickY[i-1]);
		 }else{
		   context.moveTo(clickX[i]-1, clickY[i]);
		 }
		 context.lineTo(clickX[i], clickY[i]);
		 context.closePath();
		 context.stroke();
	  }
	}
});
</script>
<style>
	#contents{ border: 1px solid blue; height: 600px}
	canvas{ 
		border:1px solid green;
		background-image: url("http://images2.wikia.nocookie.net/__cb20091228052831/leagueoflegends/images/thumb/b/b8/SummonersRift.png/602px-SummonersRift.png");
		background-size: 100% 100%; 
	}
</style>


<div id="contents">
	<canvas id="canvasInAPerfectWorld"></canvas>
</div>