									                                    
      <div class="about maincomp">
                                                                        <div class="component-pad">
                                        
<div id="page" style="height:305px">
<?php 
		echo $this->editable(
			'about_us',
			'text',
			'<h2 class="contentheadingabout">Our Company</h2>

<p class="preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>');
?>
<div class="social">
<div style="height: 24px;margin: 20px 0 0 0;padding-top: 20px;width: 206px;padding-bottom:50px;">
	<iframe allowtransparency="true" frameborder="0" scrolling="no" src="//platform.twitter.com/widgets/tweet_button.html" class="twitter-share-button twitter-count-horizontal" style="width: 110px; height: 20px; " title="Twitter Tweet Button"></iframe><iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2F<?php echo $_SERVER['HTTP_HOST'];?><?php echo $_SERVER['REQUEST_URI'];?>&amp;send=false&amp;layout=button_count&amp;width=96&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=182003968585041" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:96px; height:21px;" allowTransparency="true"></iframe>
	</div>
<p>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>

</div>


</div>

                                    </div>
      </div>
      <div class="sidemod">
      		<div class="module m abtmod1">
		
			    <div class="module-body">
	        <img src="/images/stories/abtmod.jpg">        </div>
	</div>
	
      </div>
      <div style="clear:both;"></div>
      <div id="abtmod1">
      		<div class="module">
		
			    <div class="module-body">
	       <a href="/product/multi-vitamin/id/1"><img src="/images/stories/multi.jpg"></a></div>
	</div>
	
      </div>
      <div id="abtmod2">
      		<div class="module">
		
			    <div class="module-body">
	        <a href="/product/protein/id/2"><img src="/images/stories/protien.jpg"></a>        </div>
	</div>
	
      </div>
      <div id="abtmod3">
      		<div class="module">
		
			    <div class="module-body">
	        <a href="/product/fat-burner/id/3"><img src="/images/stories/fat-burner.jpg"></a></div>
	</div>
	
      </div>
      <div style="clear:both;"></div>
      
      <div id="abtmod4">
      		<div class="module m abtmod4">
		
			    <div class="module-body">
	        <p class="preview" style="padding-top:2em"><?php echo $this->editable(
			'about_us_2',
			'text',
			'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.');
?></p></div>
	</div>
	
      </div>
      <div id="abtmod5">
      		<div class="module">
		
			    <div class="module-body">
	        <img src="/images/stories/about-image1.jpg">        </div>
	</div>
	
      </div>
      <div id="abtmod6">
      
      </div>
       <div style="clear:both;"></div>                             
																		
	</div>
	