<div id="title">
        		<div class="module m contitle">
		
			    <div class="module-body" style="font-size:30px;font-family:HelveticaLTSTDBold;color:#3E3E3E;margin-top:12px">
	        Contact        </div>
	</div>
	
        </div>
<div class="contact maincomp">
                                    		<div id="mainmods3" class="spacer w99">
					<div class="module">
		
			    <div class="module-body" style="margin-bottom:1em">
	        <span style="font-family:HelveticaBoldCondensed;">TO MAKE AN ONLINE ENQUIRY FILL OUT THE FORM BELOW.</span>        </div>
	</div>
	
			
			
		</div>
<div class="component-pad" style="padding:20px;width:560px;">
<form action="" method="post" id="contact-form">
	<p><label>First Name *</label><br>
	<input type="text" name="first_name" id="first_name"></p>
	
	<p><label>Last Name *</label><br>
	<input type="text" name="last_name" id="last_name"></p>
	
	<p><label>Email Address *</label><br>
	<input type="text" name="email" id="email"></p>
	
	<p><label>Comments/Inquiries *</label><br>
	<textarea id="comments" name="commens" rows="10"></textarea></p>
	<p><label>
		<input type="checkbox" name="subscribe" value="1" checked="checked"> 
		Subscribe to our email newsletter.
	</label></p>
	<p><button type="button" class="button">SUBMIT</button></p>
</form>
</div>
      </div>
<div class="sidemod">
      		<div class="module m contmod">
		
			    <div class="module-body">
	        <h3 style="margin-top:2px">General Inquiries</h3>

Phone +1 333 333 3333<br>
Email <a href="mailto:info@pureresults.com">info@pureresults.com</a><br>
Facebook <a href="#">facebook.com/pureresults</a><br>
Twitter <a href="#">@pureresults</a><br><br>

<h3>Order Inquiries</h3>
<a href="mailto:sales@pureresults.com">sales@pureresults.com</a>
<br>
<br>
&nbsp;&nbsp;<a href="#"><img src="/images/stories/fb.png"></a>&nbsp;&nbsp;
<a href="#"><img src="/images/stories/tw.png"></a>
<br>
<br>        </div>
	</div>
			<div class="module m contimg">
		
			    <div class="module-body">
	        <img src="/images/stories/contimg.jpg">        </div>
	</div>
	
      </div>     