<div class="left">

	<div class="content">

		<div class="page-header">
		  <h3>
		  	<?php if($this->params('id')){ ?>
		  		Update <?php echo strtolower($this->model); ?>
		  	<?php }else { ?>
		  		Add <?php echo strtolower($this->model); ?>
		  	<?php } ?>
		  </h3>
		</div>

		<div class="row">
		  	<div>
		  		<form action="/admin/product" method="POST" enctype="multipart/form-data">
		  			<input type="hidden" name="model" value="<?php echo $this->model; ?>">
		  			<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">
		  			<input type="hidden" name="user_id" value="<?php echo $this->data->row('user_id', $this->user['user_id']); ?>">
			        <fieldset>

						<legend><a name="basic_info"></a> Product info</legend>

						<div class="clearfix">
							<label for="xlInput">Name</label>
							<div class="input">
								<input class='xxlarge' name='name' value="<?php echo $this->data->row('name') ? $this->data->row('name') : ''; ?>" type='text'>
							</div>
						</div>
						<div class="clearfix">
							<label for="xlInput">Sub-Title</label>
							<div class="input">
								<input class='xxlarge' name='sub_title' value="<?php echo $this->data->row('sub_title') ? $this->data->row('sub_title') : ''; ?>" type='text'>
							</div>
						</div>
						

						<div class="clearfix">
							<label for="xlInput">Price (default)</label>
							<div class="input">
								<input class='small' name='price' value="<?php echo $this->data->row('price') ? $this->data->row('price') : ''; ?>" type='text'> <a id='add-size' href="#">Add a Size</a>
							</div>
						</div>
						
						<div id="sizes" class="clearfix">
							<label for="xlInput">Sizes</label>
							<div class="input">
								<span class="span2">Size</span>
								<span>Price</span>
							</div>
							
							<?php foreach($this->product_sizes->rows() as $product_size){?>
							<div class="input size" data-id="<?php echo $product_size['product_size_id'];?>">
								<input class='small name' name="product_size[<?php echo $product_size['product_size_id'];?>][product_size_id]" value="<?php echo $product_size['product_size_id']; ?>" type='hidden'>
								<input class='small name' name="product_size[<?php echo $product_size['product_size_id'];?>][size]" value="<?php echo $product_size['size']; ?>" type='text'>
								<input class='small price' name="product_size[<?php echo $product_size['product_size_id'];?>][price]" value="<?php echo $product_size['price']; ?>" type='text'>
							</div>
							<?php }?>
						</div>

						<div class="clearfix">
							<label for="xlInput">Description</label>
							<div class="input">
								<textarea name="description" rows='5' class='xxlarge wysiwyg' style='width:90%;'><?php echo $this->data->row('description') ? $this->data->row('description') : ''; ?></textarea>
							</div>
						</div>
						
						<div class="clearfix">
							<label for="xlInput">Amazon Url</label>
							<div class="input">
								<input type="text" name="amz_url" rows='5' class='large wysiwyg' value="<?php echo $this->data->row('amz_url') ? $this->data->row('amz_url') : ''; ?>">
							</div>
						</div>
						
						<div id="images" class="clearfix">
							<label for="xlInput">Images</label>
							<div class="input file">
								<a href="#" id="add-image" style="line-height:30px;">Add Image</a>
							</div>
							
							<div class="input">
							<?php foreach($this->product_images->rows() as $image){?>
								<img data-product_image_id="<?php echo $image['product_image_id']; ?>" style="cursor:pointer; width: 200px;" src="<?php echo $image['path'];?>" class="product-thumb">
							<?php }?>
							</div>
							
						</div>
						
			        </fieldset>

			        <fieldset>
			          <div class="actions">
			            <input type="submit" class="btn primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
			          </div>
			        </fieldset>
			      </form>
		  	</div>
		</div>

	</div>

</div>
<script>
	var product_size_counter = 0;
	$('#add-size').click( function(e){
		e.preventDefault();
		var size_html = $('<div>').addClass('input size');
		name_input = $('<input>').addClass('small name').attr('name','new_product_size[' + product_size_counter + '][size]');
		price_input = $('<input>').addClass('small price').attr('name','new_product_size[' + product_size_counter + '][price]');
		size_html.append(name_input,price_input);
		$('#sizes').append(size_html);
		product_size_counter++;
	});

	var img_counter = 0;
	$('#add-image').click( function(e){
		e.preventDefault();
		img_input = $('<input>').attr('type','file').attr('name',img_counter);
		$('#images .file').append(img_input);
		img_counter++;
	});

	$('.product-thumb').hover( function(){
		$(this).fadeTo(.01,.7);
	}, function(){
		$(this).fadeTo(.01,1);
	});

	$('.product-thumb').click( function(e){
		var $this = $(this);
		var r = confirm("Delete?");
		if(r == true){
			product_image_id = $this.attr('data-product_image_id');
			console.log(product_image_id);
			$.post('/admin/delete-product-image/', {product_image_id:product_image_id}, function(res){
				if(res.status.code == 200){
					$this.remove();
				}else{
					alert('soemthing went wrong');
				}
			});
		}
	});
</script>