<?php $product = $this->product->row();?>
<div class="maincomp">
	<div id="title">
		<div class="module m contitle">

			<div class="module-body"
				style="font-size: 39px; font-family: HelveticaLTSTDBold; color: #3E3E3E; margin-top: 18px">
				Online Store</div>
		</div>

			<br style="clear: both;">
			<div class="maindiv">
				<div class="vimage">
					<a
						href="http://worldws.com/james/components/com_virtuemart/shop_image/product/Multi_Vitamin_4f9493a1bcb79.jpg"
						title="Multi-Vitamin" rel="lightbox[product17]"><img
						src="http://worldws.com/james/components/com_virtuemart/shop_image/product/resized/Multi_Vitamin_4f9493a1a421c_642x640.jpg"
						height="640" width="642" alt="Multi-Vitamin" border="0"><br> </a>
				</div>
			</div>
			
<div id="vmMainPage">
			
			<div class="maindiv1">

				<span class="super-title">Multi-Vitamin Complex</span>
				<h1>
					<?php echo $product['name'];?>
				</h1>




				<div class="vdesc">
					<?php echo $product['description'];?>
				</div>
				<div class="vmore">more images</div>
				<div class="vaimages">
					<a
						href="http://worldws.com/james/components/com_virtuemart/shop_image/product/Untitled-1.jpg"
						title="Multi-Vitamin" rel="lightbox[product17]"><img
						src="http://worldws.com/james/components/com_virtuemart/show_image_in_imgtag.php?filename=%2Fcomponents%2Fcom_virtuemart%2Fshop_image%2Fproduct%2FUntitled-1.jpg&amp;newxsize=642&amp;newysize=640&amp;fileout="
						alt="" height="49" width="50" class="browseProductImage"
						border="0"> </a> <a
						href="http://worldws.com/james/components/com_virtuemart/shop_image/product/cake-design-10-500x375.jpg"
						title="Multi-Vitamin" rel="lightbox[product17]"><img
						src="http://worldws.com/james/components/com_virtuemart/show_image_in_imgtag.php?filename=%2Fcomponents%2Fcom_virtuemart%2Fshop_image%2Fproduct%2Fcake-design-10-500x375.jpg&amp;newxsize=642&amp;newysize=640&amp;fileout="
						alt="" height="37" width="50" class="browseProductImage"
						border="0"> </a>
				</div>
				<div class="vfile">
					<span style="font-style: italic;"></span>
				</div>

				<div class="vprice">

					<span class="productPrice"> $<?php echo $product['price'];?>
					</span> <span class="vp">USD</span>
				</div>

				<div class="vaddtocart">
					<div class="vmCartContainer">

						<form action="http://worldws.com/james/index.php" method="post"
							name="addtocart" id="addtocart_4fbc8c52a6cc3"
							class="addtocart_form"
							onsubmit="handleAddToCart( this.id );return false;">


							<div class="vmCartDetails">

								<div class="vmCartChild vmRowTwo">
									<input type="hidden" name="product_id" value="17"> <input
										type="hidden" name="prod_id[]" value="17">

									<div class="vmCartAttributes">
										<div style="float: left; margin-right:6px">
											<div class="vmAttribChildDetail">
												<label for="Size_field">Size</label>
											</div>
											<div class="vmAttribChildDetail">
												<select class="inputboxattrib" id="Size_field" name="Size17">
													<?php foreach($this->product_sizes as $size){?>
                	        	        <option value="<?php echo $size['product_size_id'];?>"><?php echo $size['size'];?></option>
                	        	<?php }?>
												</select>
											</div>
										</div>
										<div style="">
											<div class="vmAttribChildDetail">
												<label for="qty">Qty</label>
											</div>
											<div class="vmAttribChildDetail">
												<input type="text" id="qty" name="qty" maxlength="3" style="width:40px"> 
											</div>
										</div>
										
									</div>
								</div>

							</div>
								<button type="submit" class="button addtocart">Add to Cart</button>
						</form>
					</div>
				</div>

			</div>


			<br style="clear: both">
			<div class="social">
				<div
					style="height: 24px; margin: 0 0 0; padding-top: 0px; width: 275px;">
					<iframe allowtransparency="true" frameborder="0" scrolling="no"
						src="http://platform.twitter.com/widgets/tweet_button.1337330192.html#_=1337756755805&amp;count=horizontal&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=http%3A%2F%2Fuptownhr.dyndns.org%2Findex.php%3Foption%3Dcom_virtuemart%26Itemid%3D57&amp;size=m&amp;text=Multi-Vitamin&amp;url=http%3A%2F%2Fuptownhr.dyndns.org%2Findex.php%3Foption%3Dcom_virtuemart%26Itemid%3D57&amp;via=ovclinicalsops"
						class="twitter-share-button twitter-count-horizontal"
						style="width: 110px; height: 20px;" title="Twitter Tweet Button"></iframe>
					<iframe allowtransparency="" frameborder="0" scrolling="no"
						src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2F%23%21%2Fpages%2FOV-Clinical-Trials%2F195827167105791%3Fnotif_t%3Dpage_new_likes&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21"
						style="border-bottom: medium none; border-left: medium none; width: 96px; height: 21px; overflow: hidden; border-top: medium none; border-right: medium none"></iframe>
				</div>
				<p>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
				</p>

			</div>

</div>

			<div id="statusBox"
				style="text-align: center; display: none; visibility: hidden;"></div>
		</div>

	</div>
</div>
