<?php $product = $this->product->row();?>
<script type="text/javascript">
$(document).ready(function(){
	$('.browseProductImage').click(function(e) {
		e.preventDefault();
		var href = $(this).parent().attr('href');
		$('.vimage img').attr('src',href);
	});
});
</script>
<div class="maincomp">
	<div id="title">
		<div class="module m contitle">

			<div class="module-body"
				style="font-size: 39px; font-family: HelveticaLTSTDBold; color: #3E3E3E; margin-top: 18px">
				Online Store</div>
		</div>
	</div>

			<br style="clear: both;">
			<div class="maindiv">
				<div class="vimage"><img
						src="<?php echo $this->product_images[0]['path']; ?>"
						height="640" width="642" alt="Multi-Vitamin" border="0">
				</div>
			</div>
			
<div id="vmMainPage">
			
			<div class="maindiv1">

				<span class="super-title">Multi-Vitamin Complex</span>
				<h1>
					<?php echo $product['name'];?>
				</h1>




				<div class="vdesc">
					<?php echo $product['description'];?>
				</div>
				<div class="bottom" style="float: right; width: 300px;">
					<div class="vmore">more images</div>
					<div class="vaimages">
					<?php foreach($this->product_images as $images){?>
						<a href="<?php echo $images['path'];?>">
							<img
								src="<?php echo $images['path']; ?>"
								alt="" height="49" width="50" class="browseProductImage"
								border="0">
						</a>
					<?php }?>
					</div>
					<div class="vfile">
						<span style="font-style: italic;"></span>
					</div>
	
					<div class="vprice">
						<span class="productPrice"> $<?php echo $product['price'];?>
						</span> <span class="vp">USD</span>
					</div>
	
					<div class="vaddtocart">
						<div class="vmCartContainer">
	
							<form action="/cart/add" method="post" id="add_to_cart">
								<div class="vmCartDetails">
									<div class="vmCartChild vmRowTwo">
										<input type="hidden" name="product_id" value="<?php echo $product['product_id'];?>">
										<div class="vmCartAttributes">
											<div style="float: left; margin-right:6px">
												<!--
												<div class="vmAttribChildDetail">
													<label for="Size_field">Size</label>
												</div>
												<div class="vmAttribChildDetail">
													<select class="inputboxattrib" id="Size_field" name="size">
														<?php foreach($this->product_sizes as $size){?>
	                	        	        <option <?php if($product['price'] == $size['price']){ echo "selected"; }?> data-price="<?php echo $size['price'];?>" value="<?php echo $size['product_size_id'];?>"><?php echo $size['size'];?></option>
	                	        	<?php }?>
													</select>
												</div>
												-->
											</div>
											<div style="">
												<div class="vmAttribChildDetail">
													<label for="qty">Qty</label>
												</div>
												<div class="vmAttribChildDetail">
													<input type="text" id="qty" value="1" name="qty" maxlength="3" style="width:40px"> 
												</div>
											</div>
											
										</div>
									</div>
	
								</div>
									<button type="submit" class="button addtocart">Add to Cart</button>
							</form>
						</div>
					</div>
				</div>

			</div>


			<br style="clear: both">
			<div class="social">
				<div
					style="height: 24px; margin: 0 0 0; padding-top: 0px; width: 275px;">
					<iframe allowtransparency="true" frameborder="0" scrolling="no" src="//platform.twitter.com/widgets/tweet_button.html" class="twitter-share-button twitter-count-horizontal" style="width: 110px; height: 20px; " title="Twitter Tweet Button"></iframe><iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2F<?php echo $_SERVER['HTTP_HOST'];?><?php echo $_SERVER['REQUEST_URI'];?>&amp;send=false&amp;layout=button_count&amp;width=96&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=182003968585041" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:96px; height:21px;" allowTransparency="true"></iframe>
				</div>

			</div>

</div>

			<div id="statusBox"
				style="text-align: center; display: none; visibility: hidden;"></div>
		</div>

	</div>
	
	</div>
<script>
$('#add_to_cart').submit( function(e){
	var qty = $('#qty').val();
	if(qty.length < 1 || qty < 1){
		alert('Quantity is required');
		return false;
	}
});

$('#add_to_cart select').change( function(e){
	$this = $('option:selected', this);
	price = $this.attr('data-price');
	
	$('.productPrice').text( '$' + price );
});

</script>